project:
  type: website
  output-dir: docs

website:
  title: "invincible_proj"
  navbar:
    background: light
    left:
      - text: "Overview"
        href: "#overview"
      - text: "Algorithms"
        href: "#algorithms"
      - text: "Sim to Real"
        href: "#sim-to-real"
      - text: "Demo"
        href: "#demo"
      - text: "Results"
        href: "#results"
      - text: "Future Work"
        href: "#future"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    smooth-scroll: true